### ISSUE TITLE
Is there any example on callback function？

### ISSUE THREAD

**Issue by lostpupil** [fansyfs/XYAlertView#1]
I need a function perform on afterDismiss, Is there any idea about it?

**Comment by fansyfs** [comment]
sample code included in XYAlertViewDemo.xcodeproj.

// create an alertView
    XYAlertView *alertView = [XYAlertView alertViewWithTitle:@"Hello!"
                                                     message:@"This's the single alert view demo!"
                                                     buttons:[NSArray arrayWithObjects:@"Ok", @"Cancel", nil]
                                                afterDismiss:^(int buttonIndex) {
                                                    NSLog(@"button index: %d pressed!", buttonIndex);
                                                }];
    
    // set the second button as gray style
    [alertView setButtonStyle:XYButtonStyleGray atIndex:1];
    
    // display
    [alertView show];

**Comment by lostpupil** [comment]
thanks for that
